'use strict';

const OUTPUT_LIMITS = Object.freeze({
  MAX_EXPLANATIONS: 5,
  MAX_FACTS: 5,
  MAX_SUGGESTIONS: 3,
  MAX_UNCERTAINTIES: 2,
  MAX_CLAIMS_PER_EXPLANATION: 3,
  MAX_EVIDENCE_REFS_PER_CLAIM: 3,
  MAX_REASONING_REFS_PER_CLAIM: 1,
  MAX_CLAIM_LENGTH: 240,
  MAX_EXPLANATION_LENGTH: 240,
  MAX_SUGGESTION_LENGTH: 180,
  MAX_UNCERTAINTY_LENGTH: 180,
  MAX_ID_LENGTH: 120,
  MAX_TOTAL_OUTPUT_BYTES: 8192,
});

module.exports = {
  OUTPUT_LIMITS,
};
